### ISSUE TITLE
Think about research motivation

### ISSUE THREAD

**Issue by sanderhu123** [gijsmoonen/investigating-airbnb-group-06#6]

**Comment by gijsmoonen** [comment]
Iedereen voor donderdag zijn/haar laatste input geven voor research motivation

**Comment by gijsmoonen** [comment]
Aan de hand van wanneer de reviews zijn geschreven, kijken of er bepaalde spikes te vinden zijn in huur gedurende een jaar. Kijken of deze mogelijk te linken zijn aan een evenement en / of buurt in Amsterdam (e.g., gay pride of amsterdam dance event). Je zou dan op jaar basis kunnen kijken of er een patroon te vinden is in verhuur en of deze gebaseerd is op de activiteiten in de stad. 

Daarnaast zouden we de reviews per listing kunnen tellen en afzetten tegen de verhuurprijzen. Kijken of populariteit of reviews iets van invloed daar op heeft.

**Comment by Sjoerdbijlsb** [comment]
#analysis 1 Check the correlation between ADE and the amount of reviews left by guests The amount of reviews can be retrieved from the dataset. An event such as ADE might boost the motivation to leave a review, which can be further investigated.


#analysis 2 Make a price prediction in a linear regression model Right now, few prices can be retrieved from the dataset, as the data provider has fetched all the rates for a few dates in the year. Different columms such as the location, room type, and the review amount etc. could have impact on the price. To make a prediction for the prices of rooms throughout the city for next year's event, a regression analysis is run over these variables.

**Comment by anouksvh** [comment]
De impact van een event zoals ADE in Amsterdam bekijken aan de hand van de aantallen reviews. Wordt er door een event meer reviews gegeven? > wat mogelijk positieve effecten heeft op toekomstige aantal boekingen. Het gebruik van events om review rate omhoog te krijgen. Indien dit het geval is voor ADE, mogelijk verder onderzoek naar andere evenementen om bevindingen te bevestigen.
